meta_product_name: "CribCheck"
meta_title: "CribCheck - checkout your future apartment: no more surprises"
meta_description: "rate apartment and landlord to avoid bad experience"
meta_image: "cribcheck-FB-banner.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
